import path from 'path';
import fs from 'fs';
import glob from 'glob';

const BASE_GRAMMAR = './src/wgsl/grammar/wgsl.grammar';
const BASE_TOKENS = './src/wgsl/grammar/tokens.js';
const CONCRETE_GRAMMAR = './src/wgsl/highlight/wgsl.grammar';
const CONCRETE_TOKENS = './src/wgsl/highlight/tokens.js';

try {
  fs.mkdirSync('./src/wgsl/highlight', {recursive: true});
} catch (e) {};

const op = process.argv[2];

const HEADER = '// Auto-generated by use-gpu/shader build.ts. Do not edit.\n\n';

const grammar = fs.readFileSync(BASE_GRAMMAR, 'utf-8').toString();
const tokens = fs.readFileSync(BASE_TOKENS, 'utf-8').toString();

fs.writeFileSync(CONCRETE_GRAMMAR, HEADER + '@detectDelim\n' + grammar.replaceAll('comment ', 'Comment '));
fs.writeFileSync(CONCRETE_TOKENS, HEADER + tokens);
