[test]

# preload happydom for all tests
preload = ["./s2/polyfills", "./tests/happyDOM"]

# root directory
root = "./tests"

# always enable coverage
# windows tests fails when using coverage
coverage = true

# new
# coverageReporter = ["text", "lcov"]  # default ["text"]
coverageReporter = ["lcov", "text"]  # default ["text"]
coverageDir = "./coverage"  # default "coverage"
# coverageThreshold = 0.95
