name: 'Build and upload project to AWS cloud for CDN support.'
description: 'If master branch, check files do not already exist, otherwise S3 folder is the package JSON version number; If not master branch, store build in folder as hash.'
author: 's2-maps'
branding:
  icon: 'upload-cloud'
  color: 'yellow'
inputs:
  access_key_id:
    description: 'Your AWS Access Key ID'
    required: true
  secret_access_key:
    description: 'Your AWS Secret Access Key'
    required: true
  bucket:
    description: 'Your AWS bucket name'
    required: true
  bucket_location:
    description: 'Root location to store the files'
    required: true
runs:
  using: 'node16'
  main: 'configS2Action/build.js'
