name: coveralls

on: push

jobs:
  test:
    name: Coveralls Upload
    runs-on: macos-latest

    # setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install
    
    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps

    # Run all tests (both bun and playwright)

    - name: Run all tests and collect coverage
      run: bun run test:all:vitest
      timeout-minutes: 20

    # upload to Coveralls

    - name: Upload coverage to Coveralls
      run: |
        if [ -f ./coverage/lcov.info ]; then
          bun run coveralls < ./coverage/lcov.info
        fi
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
