name: Add Files to AWS CDN
on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS 16
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm i

      - name: Build
        run: node ./configS2Action/build.js
        env:
          ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: ${{ secrets.AWS_BUCKET }}
          ROOT_LOCATION: 's2maps-gl'
          BRANCH: ${{ github.ref }}
